apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "itaysass-flask.fullname" . }}
  labels:
    app: {{ include "itaysass-flask.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "itaysass-flask.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "itaysass-flask.fullname" . }}
    spec:
      containers:
        - name: flask-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "itaysass-flask.fullname" . }}-config
                  key: WELCOME_MESSAGE
            {{- if .Values.secret.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "itaysass-flask.fullname" . }}-secret
                  key: REDIS_PASSWORD
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
