apiVersion: v1
kind: Service
metadata:
  name: {{ include "itaysass-flask.fullname" . }}
  labels:
    {{- include "itaysass-flask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "itaysass-flask.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
