image:
  repository: itaysass/flask-redis-hello
  tag: "1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: NodePort
  port: 5000
  nodePort: 30001

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 500m

env:
  welcomeMessage: "Hello from ConfigMap!"

secret:
  enabled: true
  redisPassword: "password"  # demo only; override via --set or values file

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 50

containerPort: 5000
probes:
  livenessPath: /health
  readinessPath: /ready
