apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: itaysass/flask-redis-hello:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            # From ConfigMap (create k8s/configmap.yaml first)
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: WELCOME_MESSAGE
            # From Secret (reviewer asked to use secrets)
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
